### ISSUE TITLE
KDE 5.8 Support?

### ISSUE THREAD

**Issue by descendingnerdliness** [Zren/plasma-applet-volumewin7mixer#12]
The widget is reported to support KDE 5.8. On Kubuntu 16.04.3, KDE is 5.8.9, with QT 5.6.1.

The widget fails to run, with an additional requirement of QtQuick.Controls 2.0. This did not come out until QT 5.7.

**Comment by Zren** [comment]
I probably should bump the tag to KDE 5.12 since that's the latest LTS version. Even Debian moved to KDE 5.14 from KDE 5.8 recently. I don't know how long Kubuntu 16.04 is supported, I thought it was only 3 years. Canonical/Ubuntu will patch the applications, but I don't think the KDE software will be updated anymore.

* https://repology.org/project/plasma-desktop/versions
* https://askubuntu.com/questions/967169/why-does-kubuntu-and-xubuntu-16-04-lts-support-end-sooner-than-the-official-ubun
* https://kubuntu.org/news/trusty-14-04-lts-end-of-life-and-end-of-kubuntu-support-for-xenial-16-04-lts/
* https://community.kde.org/Schedules/Plasma_5

As for fixing it on your computer for the short term, I'm not certain which was the last version of the widget that supported KDE 5.8 for you to roll back to, as I can't find where I import `QtQuick.Controls 2.0`. Could you tell me which file specifically is telling you there's an error loading the import?

**Comment by descendingnerdliness** [comment]
I apologize for not getting back to you sooner. I am in the midst of a very slow going transition to to Manjaro, bcache, and btrfs. My system was down for a good while to deal with read errors on a 3 terabyte drive. 

The transition also required some utilities that would not run on 16.04, so I upgraded Kubuntu to 18.04, which does meet the requirements of Win 7 Volume Mixer, for the interim. 

As a result, I cannot answer your question. But now, I can see that you have done an excellent work. Thank you! 

Soon, I will be able to try it on Manjaro and can report back it you would like. It seems that dealing with the audio on Linux is an art as well as a science, so you and anyone who can deserves congratulations.
